// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace hier_beta_geom_model_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 39> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 36, column 4 to column 24)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 37, column 4 to column 23)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 55, column 4 to column 35)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 57, column 8 to column 86)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 56, column 25 to line 58, column 5)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 56, column 4 to line 58, column 5)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 41, column 4 to column 40)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 42, column 4 to column 76)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 43, column 4 to column 41)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 45, column 8 to column 58)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 46, column 8 to column 69)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 44, column 23 to line 47, column 5)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 44, column 4 to line 47, column 5)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 49, column 4 to column 46)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 50, column 4 to column 60)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 23, column 4 to column 23)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 24, column 4 to column 25)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 26, column 10 to column 15)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 26, column 4 to column 35)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 27, column 4 to column 26)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 31, column 1 to column 33)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 32, column 1 to column 31)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 55, column 10 to column 17)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 3, column 8 to column 17)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 9, column 12 to column 38)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 8, column 15 to line 10, column 9)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 7, column 12 to column 50)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 6, column 27 to line 8, column 9)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 6, column 15 to line 10, column 9)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 5, column 12 to column 34)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 4, column 20 to line 6, column 9)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 4, column 8 to line 10, column 9)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 11, column 8 to column 19)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 2, column 48 to line 12, column 5)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 15, column 8 to column 73)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 16, column 8 to line 17, column 67)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 18, column 8 to column 24)",
  " (in '/Users/masoerl/PredictNewCustomers/code_AISTATS/utils_folder/hier_beta_geom_model.stan', line 14, column 55 to line 19, column 5)"};
template <bool propto__, typename T0__, typename T1__, typename T2__,
          stan::require_all_t<std::is_integral<T0__>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>>* = nullptr>
stan::promote_args_t<T1__>
trunc_geom_lpmf(const T0__& y, const T1__& pi, const T2__& d, std::ostream*
                pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>, std::is_integral<T3__>>* = nullptr>
stan::promote_args_t<T0__, T1__>
q0(const T0__& alpha, const T1__& beta, const T2__& d, const T3__& dfollow,
   std::ostream* pstream__);
// real trunc_geom_lpmf(int, real, int)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          stan::require_all_t<std::is_integral<T0__>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>>*>
stan::promote_args_t<T1__>
trunc_geom_lpmf(const T0__& y, const T1__& pi, const T2__& d, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ out = DUMMY_VAR__;
    current_statement__ = 32;
    if (stan::math::logical_eq(y, 0)) {
      current_statement__ = 30;
      out = (d * stan::math::log((1 - pi)));
    } else {
      current_statement__ = 29;
      if (stan::math::logical_lte(y, d)) {
        current_statement__ = 27;
        out = (((y - 1) * stan::math::log((1 - pi))) + stan::math::log(pi));
      } else {
        current_statement__ = 25;
        out = stan::math::negative_infinity();
      }
    }
    current_statement__ = 33;
    return out;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real q0(real, real, int, int)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>, std::is_integral<T3__>>*>
stan::promote_args_t<T0__, T1__>
q0(const T0__& alpha, const T1__& beta, const T2__& d, const T3__& dfollow,
   std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ out = DUMMY_VAR__;
    current_statement__ = 35;
    out = (stan::math::lgamma(((beta + d) + dfollow)) +
      stan::math::lgamma(((alpha + beta) + d)));
    current_statement__ = 36;
    out = (out - (stan::math::lgamma((((alpha + beta) + d) + dfollow)) +
      stan::math::lgamma((beta + d))));
    current_statement__ = 37;
    return stan::math::exp(out);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class hier_beta_geom_model_model final : public model_base_crtp<hier_beta_geom_model_model> {
 private:
  int Ndays;
  int Nfollow;
  std::vector<int> users_per_day;
  int n_notrig;
  int n_trig;
  int Ndata;
 public:
  ~hier_beta_geom_model_model() {}
  hier_beta_geom_model_model(stan::io::var_context& context__, unsigned int
                             random_seed__ = 0, std::ostream*
                             pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "hier_beta_geom_model_model_namespace::hier_beta_geom_model_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 16;
      context__.validate_dims("data initialization", "Ndays", "int",
        std::vector<size_t>{});
      Ndays = std::numeric_limits<int>::min();
      current_statement__ = 16;
      Ndays = context__.vals_i("Ndays")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "Ndays", Ndays, 0);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "Nfollow", "int",
        std::vector<size_t>{});
      Nfollow = std::numeric_limits<int>::min();
      current_statement__ = 17;
      Nfollow = context__.vals_i("Nfollow")[(1 - 1)];
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "Nfollow", Nfollow, 0);
      current_statement__ = 18;
      stan::math::validate_non_negative_index("users_per_day", "Ndays", Ndays);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "users_per_day", "int",
        std::vector<size_t>{static_cast<size_t>(Ndays)});
      users_per_day = std::vector<int>(Ndays,
                        std::numeric_limits<int>::min());
      current_statement__ = 19;
      users_per_day = context__.vals_i("users_per_day");
      current_statement__ = 20;
      context__.validate_dims("data initialization", "n_notrig", "int",
        std::vector<size_t>{});
      n_notrig = std::numeric_limits<int>::min();
      current_statement__ = 20;
      n_notrig = context__.vals_i("n_notrig")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "n_notrig", n_notrig, 0);
      current_statement__ = 21;
      n_trig = std::numeric_limits<int>::min();
      current_statement__ = 21;
      n_trig = stan::math::sum(users_per_day);
      current_statement__ = 22;
      Ndata = std::numeric_limits<int>::min();
      current_statement__ = 22;
      Ndata = (n_trig + n_notrig);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("n_new_users", "Nfollow",
        Nfollow);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "hier_beta_geom_model_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hier_beta_geom_model_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      {
        current_statement__ = 7;
        lp_accum__.add((-(2.5) * stan::math::log((alpha + beta))));
        current_statement__ = 8;
        lp_accum__.add((Ndata * ((stan::math::lgamma((alpha + beta)) -
          stan::math::lgamma(alpha)) - stan::math::lgamma(beta))));
        current_statement__ = 9;
        lp_accum__.add((n_trig * stan::math::lgamma((alpha + 1))));
        current_statement__ = 13;
        for (int i = 1; i <= Ndays; ++i) {
          current_statement__ = 10;
          lp_accum__.add((stan::model::rvalue(users_per_day, "users_per_day",
                            stan::model::index_uni(i)) *
            stan::math::lgamma((beta + (i - 1)))));
          current_statement__ = 11;
          lp_accum__.add(((-(1.0) *
            stan::model::rvalue(users_per_day, "users_per_day",
              stan::model::index_uni(i))) *
            stan::math::lgamma(((alpha + beta) + i))));
        }
        current_statement__ = 14;
        lp_accum__.add((n_notrig * stan::math::lgamma((beta + Ndays))));
        current_statement__ = 15;
        lp_accum__.add(((-(1.0) * n_notrig) *
          stan::math::lgamma(((alpha + beta) + Ndays))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hier_beta_geom_model_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      {
        current_statement__ = 7;
        lp_accum__.add((-(2.5) * stan::math::log((alpha + beta))));
        current_statement__ = 8;
        lp_accum__.add((Ndata * ((stan::math::lgamma((alpha + beta)) -
          stan::math::lgamma(alpha)) - stan::math::lgamma(beta))));
        current_statement__ = 9;
        lp_accum__.add((n_trig * stan::math::lgamma((alpha + 1))));
        current_statement__ = 13;
        for (int i = 1; i <= Ndays; ++i) {
          current_statement__ = 10;
          lp_accum__.add((stan::model::rvalue(users_per_day, "users_per_day",
                            stan::model::index_uni(i)) *
            stan::math::lgamma((beta + (i - 1)))));
          current_statement__ = 11;
          lp_accum__.add(((-(1.0) *
            stan::model::rvalue(users_per_day, "users_per_day",
              stan::model::index_uni(i))) *
            stan::math::lgamma(((alpha + beta) + i))));
        }
        current_statement__ = 14;
        lp_accum__.add((n_notrig * stan::math::lgamma((beta + Ndays))));
        current_statement__ = 15;
        lp_accum__.add(((-(1.0) * n_notrig) *
          stan::math::lgamma(((alpha + beta) + Ndays))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "hier_beta_geom_model_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      out__.write(alpha);
      out__.write(beta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<int> n_new_users =
        std::vector<int>(Nfollow, std::numeric_limits<int>::min());
      current_statement__ = 6;
      for (int i = 1; i <= Nfollow; ++i) {
        current_statement__ = 4;
        stan::model::assign(n_new_users, (n_notrig -
          stan::math::binomial_rng(n_notrig,
            q0(alpha, beta, Ndays, i, pstream__), base_rng__)),
          "assigning variable n_new_users", stan::model::index_uni(i));
      }
      out__.write(n_new_users);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 2;
      beta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{});
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 2;
      beta = context__.vals_r("beta")[(1 - 1)];
      out__.write_free_lb(0, beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "beta"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"n_new_users"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(Nfollow)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= Nfollow; ++sym1__) {
        param_names__.emplace_back(std::string() + "n_new_users" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= Nfollow; ++sym1__) {
        param_names__.emplace_back(std::string() + "n_new_users" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"n_new_users\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nfollow) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"n_new_users\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nfollow) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (Nfollow);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (Nfollow);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = hier_beta_geom_model_model_namespace::hier_beta_geom_model_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return hier_beta_geom_model_model_namespace::profiles__;
}
#endif