#!/usr/bin/env python3
"""
Generate LaTeX macros from committed result CSVs so the paper never hard-codes a number.

Reads   : results/rees46_experiment_counts.csv
          results/hitting_time_mae_asos.csv
          results/hitting_time_mae_k100.csv
Writes  : latex/values/generated_values.tex   (a block of \newcommand macros)

The paper \input{values/generated_values.tex} and uses the macros in place of literals.
Rounding is applied HERE to match how the value is displayed (MAE to 1 decimal; counts as
integers); the CSVs keep full precision. Re-run whenever the CSVs change and commit together.

This is the first slice of the reproducibility plumbing; extend as more CSVs land
(cross-dataset accuracy, case studies, proprietary aggregates, ...).
"""
import os
import csv

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # SubmissionAOAS/
RES = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "latex", "values", "generated_values.tex")

# --- macro-name-safe maps (TeX macro names must be letters only) ---
METHOD = {
    "NB-SSP (reg)": "NBSSP",
    "TG-SSP": "TGSSP",
    "IBP": "IBP",
    "Linear extrap.": "Lin",
    "Jackknife (J3)": "Jack",
}
ETA = {"1.5": "A", "2.0": "B", "3.0": "C"}  # 1.5 / 2 / 3

lines = []
lines.append("% AUTO-GENERATED by scripts/gen_paper_values.py -- DO NOT EDIT BY HAND.")
lines.append("% Every value below traces to a committed CSV in results/. Re-run the")
lines.append("% generator and recommit when the CSVs change.")
lines.append("")


def newcmd(name, value):
    lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")


# --- 1. REES46 rolling-window counts ---
with open(os.path.join(RES, "rees46_experiment_counts.csv")) as f:
    kmap = {21: "KtwentyOne", 50: "Kfifty", 100: "Khundred"}
    dtotal = None
    lines.append("% REES46 rolling-window counts (results/rees46_experiment_counts.csv)")
    for row in csv.DictReader(f):
        k = int(row["k"])
        dtotal = int(row["D_total"])
        newcmd(f"Nexp{kmap[k]}", int(row["n_experiments"]))
    newcmd("DtotalRees", dtotal)
    lines.append("")


# --- 2. Hitting-time MAE tables (results/hitting_time_mae_{asos,k100}.csv) ---
def load_ht(path, dataset_tag):
    lines.append(f"% Hitting-time MAE, {dataset_tag} ({os.path.basename(path)})")
    with open(path) as f:
        for row in csv.DictReader(f):
            m = METHOD[row["method"]]
            e = ETA[row["eta"]]
            mae = f"{float(row['mae']):.1f}"
            newcmd(f"htMAE{dataset_tag}{m}{e}", mae)
    lines.append("")


load_ht(os.path.join(RES, "hitting_time_mae_asos.csv"), "Asos")
load_ht(os.path.join(RES, "hitting_time_mae_k100.csv"), "Rees")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {OUT}\n")
print("\n".join(lines))
